### ISSUE TITLE
[meta] Working on restricting funtions

### ISSUE THREAD

**Issue by iam-py-test** [donno2048/restricted-functions#1]
This is a meta issue for working on this project

**Comment by donno2048** [comment]
- [x] os.system
- [x] os.rmdir
- [x] subprocess.run
- [x] subprocess.call
- [x] subprocess.check_output
- [ ] shutil.rmtree

What else?

**Comment by iam-py-test** [comment]
@donno2048 it seems that sandboxing python is  a better alternative (for this).
Do you want to continue on this (maybe just because it is an interesting project)?
The list posted sounds ok, but I think subprocess.run should be added:
https://docs.python.org/3.8/library/subprocess.html#subprocess.run

**Comment by donno2048** [comment]
> Do you want to continue on this (maybe just because it is an interesting project)?

I'm interested in this, and it can be in use some for some of my projects too, if you don't want to work on it it's fine

> The list posted sounds ok, but I think subprocess.run should be added

It is already listed

**Comment by iam-py-test** [comment]
> > Do you want to continue on this (maybe just because it is an interesting project)?
> 
> I'm interested in this, and it can be in use some for some of my projects too, if you don't want to work on it it's fine
> 
> > The list posted sounds ok, but I think subprocess.run should be added
> 
> It is already listed

Whoops! Sorry I missed that.
I would like to keep working on this, as it is a cool project
<details>
<summary>Irrelevant</summary>
What are your pronouns? I would like to know how to refer to you, and I don't want to make a mistake. 
</details>

**Comment by donno2048** [comment]
> I would like to keep working on this, as it is a cool project

Great!

**Comment by donno2048** [comment]
I just restricted `shutil.rmtree` - d46397d

I guess there are three more things left to do:

- [ ] Get more dangerous functions
- [ ] Make it work by simply importing it (which should be easy since we are already able to modify the import statement)
- [ ] Possibly creating a package

**Comment by donno2048** [comment]
I think we need to keep using pull requests because these tasks may collide

**Comment by iam-py-test** [comment]
How can we make a package? I am not familiar with that, so I will need your help.
I will do some research onto dangerous functions; maybe we could create a .txt or .md file just to keep track.

I agree that we should use Pull Requests, that sounds like a good idea.

**Comment by iam-py-test** [comment]
Also, sorry for accidently editing your comment; I did not realize that (strangely) clicking on it modified it but I undid my changes

**Comment by iam-py-test** [comment]
I don't know how much breakage this would cause, but maybe we should also consider os.remove.
Maybe we could also create _security levels_ or something so the user can device how high they want their protection

**Comment by donno2048** [comment]
> How can we make a package? I am not familiar with that, so I will need your help.

I will take care of creating the package

> I will do some research onto dangerous functions; maybe we could create a .txt or .md file just to keep track.

I will write this in a _TODO.md_

> I agree that we should use Pull Requests, that sounds like a good idea.

I think we should create branches for each task then merge them when we're done

**Comment by iam-py-test** [comment]
@donno2048 what about os.unlink? It seems to be fairly dangerous according to https://docs.python.org/3.8/library/os.html#os.unlink

**Comment by donno2048** [comment]
> I don't know how much breakage this would cause, but maybe we should also consider os.remove.
> Maybe we could also create _security levels_ or something so the user can device how high they want their protection

That sounds awesome, but it will take more time (obviously)

**Comment by donno2048** [comment]
@iam-py-test gather some functions, I will open a _TODO_ just add them there...

**Comment by donno2048** [comment]
> @iam-py-test gather some functions, I will open a _TODO_ just add them there...

Done

**Comment by iam-py-test** [comment]
Opened pullrequest #4

**Comment by iam-py-test** [comment]
Is it possible to use pip yet to install it?
Edit: I can & just did

**Comment by donno2048** [comment]
You could use the original pip command or use `pip install git+https://github.com/donno2048/restricted-functions/`

**Comment by iam-py-test** [comment]
@donno2048 when I did `python` and then tried to import it into the interactive python interface, I got this error:
```bash
~ $ python
Python 3.9.0 (default, Feb 27 2021, 09:11:50) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import restricted-functions
  File "<stdin>", line 1
    import restricted-functions
                     ^
SyntaxError: invalid syntax

```

**Comment by iam-py-test** [comment]
The install worked, the import didn't.
For some reason, I can't upload screenshots to GitHub on this device, but I hope the log helps

**Comment by donno2048** [comment]
```py
import ref
```

**Comment by iam-py-test** [comment]
Sorry, forgot.
Is there a way the import can be changed to avoid conflict?

Apart from forgetting to import it correctly, it worked perfectly.

**Comment by donno2048** [comment]
> Is there a way the import can be changed to avoid conflict?

Yeah,

https://github.com/donno2048/restricted-functions/issues/6#issuecomment-862520188

I asked you if there is a name you would like better, the current name is just as a place-holder for now...

**Comment by iam-py-test** [comment]
> > Is there a way the import can be changed to avoid conflict?
> 
> Yeah,
> 
> [#6 (comment)](https://github.com/donno2048/restricted-functions/issues/6#issuecomment-862520188)
> 
> I asked you if there is a name you would like better, the current name is just as a place-holder for now...

Sorry I did not respond. 
We could use `restrictfunction`, `restrictingfunctions`, `restrictfunctions`, `restrictfunctionsinterface`, or (if you have a better name) something else.
I am ok with almost any name

**Comment by donno2048** [comment]
I think it's better be a short name...

Anyway, it's 2am here, I probably should sleep by now, see you tomorrow...

**Comment by iam-py-test** [comment]
Ok! We can work on this tomorrow

**Comment by iam-py-test** [comment]
Should sys.exit be considered as it does terminate the program, or would that cause too much breakage?

**Comment by donno2048** [comment]
I think all the functions we have added can be "level zero restriction" and function which can modify files can be "level one restriction" and `os.fork` and such should be considered "level two restriction" but I don't think `sys.exit` is harmful, it's a legit function...

**Comment by iam-py-test** [comment]
@donno2048 if we are blocking write (but not read) access to files at a higher level, how would we do that?
Would something like this work:
```python
orOpen = open
def open(filename,action):
      if action == "w" or action == "a" or action == "wb":
           return None
      return orOpen(filename,action)
```

**Comment by donno2048** [comment]
We should do something like that:

```py
def open_(filename, mode="r", *args, **kwargs):
     if "w" in mode or "a" in mode: raise AttributeError()
     return open(filename, mode, *args, **kwargs)
__builtins__.open = open_
```

I'm not near my PC to test it, but it should work,
BTW, don't remove the `_` to make it uneditable.

**Comment by iam-py-test** [comment]
Ok! Should we have a flag on the `main` function (i.e. `restrictwrite` or `allowwrite`) to enable that?
Should `os.removedirs` be added as well as it is basically a more powerful os.rmdir?

**Comment by donno2048** [comment]
We really should add `os.removedirs` to this list, creating a flag for each purpose sounds pretty complicated (not for us, but rather to use), anyway, it's probably better than creating a tier list of restrictions which cannot really be treated as a "continues ranking" if you know what I mean, after all I do think it should be an optional variable ("flag")

**Comment by iam-py-test** [comment]
> We really should add `os.removedirs` to this list, creating a flag for each purpose sounds pretty complicated (not for us, but rather to use), anyway, it's probably better than creating a tier list of restrictions which cannot really be treated as a "continues ranking" if you know what I mean, after all I do think it should be an optional variable ("flag")

Oh. PR #13  corrected

**Comment by donno2048** [comment]
We really should add `os.removedirs` to this list, creating a flag for each purpose sounds pretty complicated (not for us, but rather to use), anyway, it's probably better than creating a tier list of restrictions which cannot really be treated as a "continues ranking" if you know what I mean, after all I do think it should be an optional variable ("flag")

**Comment by iam-py-test** [comment]
Do you think it is time to create a first release?

**Comment by donno2048** [comment]
There is an alpha already (to allow the `pip` installation) but sure, maybe as a `pre-release`  like a beta version until some actual security levels will be introduced

**Comment by iam-py-test** [comment]
> There is an alpha already (to allow the `pip` installation) but sure, maybe as a `pre-release` like a beta version until some actual security levels will be introduced

Ok.
I added a test on Windows to make sure it works across more than one platform

**Comment by donno2048** [comment]
Done

**Comment by iam-py-test** [comment]
How do you want to do the Docs? Should we use the README.md or GitHub's Wiki feature?

**Comment by donno2048** [comment]
I think we should use docstrings, then we can automate the creation of the documentation, then, the README is probably better, because it supports different platforms.

**Comment by iam-py-test** [comment]
> I think we should use docstrings, then we can automate the creation of the documentation, then, the README is probably better, because it supports different platforms.

What are docstrings? How do we set it up?

**Comment by donno2048** [comment]
If you have a function `fun` you can document it like so:

```py
"""!!
# some docs
```py
this is markdown docs
` ``
"""
def fun():
    """plain text short docs"""
    pass
```

**Comment by iam-py-test** [comment]
I have made some updates to the README. Does #14 look ok?

**Comment by donno2048** [comment]
a3ef98c

**Comment by donno2048** [comment]
We need to split the functions into two (or more) levels and implement it

**Comment by donno2048** [comment]
I will close this issue, when another function pops up, we can add it right away (or create a new conversation).

When #17 will be resolved we will create the first official release.

**Comment by iam-py-test** [comment]
@donno2048 do you think we should implement a _silent mode_ where it just silently fails instead of throwing an error?

**Comment by donno2048** [comment]
We can add a wrapper `silent` which to silent everything which only being applied when silent mode is being activated, sure

**Comment by iam-py-test** [comment]
Created #19 to implement it

**Comment by iam-py-test** [comment]
Do you think we should add `shutil.move`, and if so, should it be under `protectdirs` or `protectfiles` (or both, as it can move both dirs & files)?
Also, what do you think about a logging mode, where violations are logged via print.
I was thinking that could be used by developers to debug their programs without allowing a bug to do harm to their system.

**Comment by iam-py-test** [comment]
@donno2048 an library we (maybe) should block; multiprocessing
It is used in Cryptomining & deals with OS level processes.

Also, (I don't know if there is anything we can do) but someone can use banned functions if imported before ref.
If there is nothing we can do, maybe the Docs should be updated to say that it needs to be put at the top

**Comment by donno2048** [comment]
> Do you think we should add `shutil.move`, and if so, should it be under `protectdirs` or `protectfiles` (or both, as it can move both dirs & files)?

We should add it along with `os.rename` and `os.replace` in both

> Also, what do you think about a logging mode, where violations are logged via print.
> I was thinking that could be used by developers to debug their programs without allowing a bug to do harm to their system.

I think it's a bad idea because first, it can be implemented by the user, and secondly (and more important) it'll not be possible to use this without setting `silent` to `True` which is counterintuitive when dealing with flags (that is the reason I didn't suggest to auto-set `protectfiles` when `protectdirs` is being used

**Comment by iam-py-test** [comment]
Added os.rename, os.replace, and shutil.move in https://github.com/donno2048/restricted-functions/commit/4f6ea3ac5e0eb131161db55dbe61c6cf3691cebc

**Comment by donno2048** [comment]
> @donno2048 an library we (maybe) should block; multiprocessing
> It is used in Cryptomining & deals with OS level processes.

It's legit, we shouldn't ban essential functions/modules because they can cause an adverse impact which isn't a vulnerability
 
> Also, (I don't know if there is anything we can do) but someone can use banned functions if imported before ref.

Obviously, ref isn't being used then


> If there is nothing we can do, maybe the Docs should be updated to say that it needs to be put at the top

I thought it's clear, but if not we can add it

**Comment by iam-py-test** [comment]
Are shutil.rename & shutil.replace real functions?
For some reason they were added in https://github.com/donno2048/restricted-functions/commit/4f6ea3ac5e0eb131161db55dbe61c6cf3691cebc (probably a weird malfunction or typo?)
Edit: they don't look like they are.

**Comment by donno2048** [comment]
> Are shutil.rename & shutil.replace real functions?
> For some reason they were added in [4f6ea3a](https://github.com/donno2048/restricted-functions/commit/4f6ea3ac5e0eb131161db55dbe61c6cf3691cebc) (probably a weird malfunction or typo?)
> Edit: they don't look like they are.

530d2cd1af767f3b88ecc4916e778d1fffdf1798

**Comment by iam-py-test** [comment]
Added a small note in https://github.com/donno2048/restricted-functions/commit/5a9fafeb4f2ecf732de3e7c31f4541bc82a1b9da to inform people that they need to put it at the top

**Comment by iam-py-test** [comment]
Another function; `subprocess.Popen`
According to https://stackoverflow.com/questions/8217613/how-to-get-data-from-command-line-from-within-a-python-program, it can be used to run commands (maybe similar to os.Popen?)

**Comment by iam-py-test** [comment]
All functions have been added; closing

**Comment by yuvy** [comment]
Hi, I am trying to use `refs` but getting an error `RecursionError: maximum recursion depth exceeded` when using `open` - can you help with this ?

Example:
`
    __ref__(ref._ProtectFiles)

    with open('file_name',  'r') as fp:

        data = fp.read()

    print(data)
`

Error: `RecursionError: maximum recursion depth exceeded`

**Comment by iam-py-test** [comment]
@yuvy we will look into that.
Would you mind opening another issue?
What OS are you on?

**Comment by iam-py-test** [comment]
@donno2048 @yuvy I can reproduce on Raspberry Pi OS.

**Comment by iam-py-test** [comment]
@donno2048 another function:
os.popen2

**Comment by donno2048** [comment]
> Hi, I am trying to use `refs` but getting an error `RecursionError: maximum recursion depth exceeded` when using `open` - can you help with this ?
> 
> Example:
> `
> **ref**(ref._ProtectFiles)
> 
> ```
> with open('file_name',  'r') as fp:
> 
>     data = fp.read()
> 
> print(data)
> ```
> 
> `
> 
> Error: `RecursionError: maximum recursion depth exceeded`


Fixed on #26

**Comment by donno2048** [comment]
> @donno2048 another function:
> os.popen2

66ffd5d
